<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sun, 31 Jul 2016 13:18:51 +0000
 */

$conf['title'] = 'TechNotes';
$conf['lang'] = 'zh';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['markdownextra']['frontmatter'] = 1;
$conf['plugin']['discussion']['automatic'] = 1;

// end auto-generated content
